# Generated by Django 4.1 on 2022-08-31 19:58

from django.db import migrations, models
import server.apps.lecturers.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=60, verbose_name='First name')),
                ('last_name', models.CharField(max_length=60, verbose_name='Last name')),
                ('dob', models.DateField(verbose_name='Date of birth')),
                ('department', models.CharField(max_length=120, verbose_name='Department')),
                ('photo', models.ImageField(upload_to=server.apps.lecturers.models.lecturer_image_file, verbose_name='Photo')),
            ],
        ),
    ]
