# Generated by Django 4.1 on 2022-08-31 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member', models.CharField(max_length=60, verbose_name='Member')),
                ('department', models.CharField(blank=True, max_length=120, verbose_name='Department')),
                ('programme', models.CharField(blank=True, max_length=120, verbose_name='Program of study')),
                ('semester_year', models.CharField(max_length=60, verbose_name='Semester year')),
                ('semester', models.IntegerField(default=1, verbose_name='Semester')),
                ('attendance', models.IntegerField(default=1, verbose_name='Expected attendance')),
                ('is_current', models.BooleanField(default=False, verbose_name='is_current')),
            ],
            options={
                'verbose_name': 'Semester',
                'verbose_name_plural': 'Semesters',
            },
        ),
    ]
